name: On push for app

on:
  push:
    branches: [main]

jobs:
 call-workflow:
    uses: jbenaventem/test-workflow-reusable/.github/workflows/ci-cd.yml@main

    with:
      project: app-test
      target: ${{ github.ref_name }}